### PR TITLE
Add flag to check if files are formatted

### PR DESCRIPTION
**Pull request by ratsclub**
This is a follow-up PR for #91.

About the flag name, what do you think of `--dryrun`?

### CODE REVIEW

**Comment by ratsclub** [comment]
Another issue I'm facing is that the pretty output doesn't have a break line at the end of the file. Do you think we should trim the original one in order to compare?

**Comment by shwestrick** [comment]
> Another issue I'm facing is that the pretty output doesn't have a break line at the end of the file. Do you think we should trim the original one in order to compare?

I think the formatted output should always be exactly `result ^ "\n"` -- does that work?

**Comment by shwestrick** [comment]
> About the flag name, what do you think of `--dryrun`?

I like it, although I think the name "dry run" suggests that it will tell us exactly what changes a normal run would make. (For example, `git clean --dry-run`.)

This wouldn't be a huge change; it would just require not immediately failing on the first file, and instead allowing the tool to continue.

The output could be something like:
```
Would modify foo.sml
Would modify bar.sml
```

Thoughts?

**Comment by ratsclub** [comment]
@shwestrick Would you be open to give this the `--check` flag? Other tools that use it:

- [black](https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#check)
- [rustfmt](https://github.com/rust-lang/rustfmt#verifying-code-is-formatted)
- [fantomas](https://fsprojects.github.io/fantomas/docs/end-users/FormattingCheck.html#check)

In this case, I suggest changing the current `--check` to `--safety-check`.

**Comment by shwestrick** [comment]
> @shwestrick Would you be open to give this the `--check` flag? Other tools that use it:
> 
> * [black](https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#check)
> * [rustfmt](https://github.com/rust-lang/rustfmt#verifying-code-is-formatted)
> * [fantomas](https://fsprojects.github.io/fantomas/docs/end-users/FormattingCheck.html#check)

Oh excellent, I like it. Let's use `--check` then.

> In this case, I suggest changing the current `--check` to `--safety-check`.

Sounds good to me!

**Comment by ratsclub** [comment]
@shwestrick May you check if this is good enough?

**Comment by shwestrick** [comment]
Just did a little testing and found a bug. (This file should pass.)
```bash
$ ./smlfmt --check src/base/MLtonPathMap.sml
ERROR: Unformatted file 'src/base/MLtonPathMap.sml'
```

The issue appears to be on this line:
```
val original = TextIO.input (TextIO.openIn hfp)
```

This is subtle, but `TextIO.input` doesn't guarantee that you get *all* the input (there's a different function in `TextIO` for that).

If I switch to this instead, it seems to work:
```
val original = ReadFile.contents hfp
```

([`ReadFile.contents`](https://github.com/shwestrick/smlfmt/blob/6158c551766865d7184624656a938edb73bd588c/src/base/ReadFile.sml#L12) is usually faster, gets the entire contents, and also guarantees that the opened file is closed before returning.)

Could you make that change? Then I think we're good to merge.

**Comment by ratsclub** [comment]
> This is subtle, but TextIO.input doesn't guarantee that you get all the input.
This is surprising and good to know. Do you have any place where I can read more about that?

> Could you make that change? Then I think we're good to merge.
Done.

**Comment by shwestrick** [comment]
The [official docs](https://smlfamily.github.io/Basis/imperative-io.html#SIG:IMPERATIVE_IO.input:VAL) for `TextIO.input` are a bit vague but technically allow for this behavior: "... returns a vector of at least one element"

Moscow ML's description [here](https://www.itu.dk/~sestoft/mosmllib/TextIO.html) is perhaps at little better: "... returns some elements from [the stream]"

My understanding is that this function has a very particular intended mode-of-use, where you call `TextIO.input(...)` in a loop until it returns an empty string. This would let you incrementally process characters from a large file without needing the entire string in memory all at once. (There is a separate function `TextIO.inputAll` which gets you the entire string.)

The naming is unfortunate (the name `input` is unassuming but the function is very niche), and I wish the docs were more clear. Perhaps it all made a bit more sense back in the 80s and 90s when the Basis Library was designed. In 2023, I find it a bit strange. Oh well 🤷‍♂️

**Comment by shwestrick** [comment]
Thanks for putting this together, it looks great! Merging now.

**Pull request merged**
