### PR TITLE
(WIP) safety checks

### PR DESCRIPTION
**Pull request by shwestrick**
Progress on #43. This patch implements a flag `--check` which, before writing to the output, checks the following:
  * `lex(output) = lex(input)`: no tokens added, removed, or reordered (including comments).
  * `parse(output) = parse(input)`: make sure nothing terrible has gone wrong in the parser. (If the result of the lexer is good, then this check should be superfluous. But, uhhh, for my sanity... I'm just gonna check it explicitly.)
  * `format(output) = format(input)`: make sure the formatter is idempotent.

Together, these checks should ensure that `smlfmt` is always safe to use. The first two checks are crucial, whereas the idempotence check is moreso an aesthetic concern. And actually, I've found a few edge cases where `smlfmt` is not idempotent, due to how comments are handled. (We should fix that later.)

So, for now, with `--check` enabled, `smlfmt` will exit with an error if safety is violated (i.e., due to tokens mangled), and will only output a warning if idempotence is violated.

- [x] `CheckOutput.check` interface
- [x] `--check` flag, and plumbing for calling `CheckOutput.check` in the right place
- [x] ~implement `CheckOutput.checkTokenSeqs.checkTokens`~. Implement `Token.sameExceptForMultilineIndentation`, which compares two tokens, handling multiline tokens where it's okay for indentation to differ.
- [x] implement `CompareAst`.
- [x] check for bugs from existing tests

### CODE REVIEW

**Comment by azdavis** [comment]
this is nifty, once impl'd i'll probably call smlfmt from millet with this flag and move the disclaimer to only apply to my naive formatter.

can there be specific exit codes so a caller of smlfmt (like millet) can tell the difference between user error (e.g. parse error) and smlfmt internal error (e.g. `lex(output) != lex(input)` etc)? that way millet could ignore smlfmt errors about bad user input but show a warning/request the user fill out a bug report when smlfmt fails the safety checks.

**Comment by azdavis** [comment]
that sounds nice but also a lot more work

**Comment by shwestrick** [comment]
On the `smlfmt` side, it would be really easy to do an initial protocol. I'm picturing just three possible messages initially:
  * success with formatted output, e.g. `{ "tag": "success", "data": ... }`
  * error: invalid SML input `{ "tag": "parse-error", "data": ... }`
  * error: smlfmt bug `{ "tag": "bug", "data": ... }`

Would this be difficult to support on Millet's side?

(I think it's worth the investment, because then the protocol could be incrementally extended with more interesting functionality down the line.)

**Comment by azdavis** [comment]
oh no it wouldn't really be much harder to consume that on the millet side. the 'more work' i was thinking of would be smlfmt  being able to input/output incremental diffs.

i'd suggest a flag like `--json-version=<N>` where `<N>` is some integer starting with 1 to output json data. then if you need to change the output in a backwards incompatible way you can request new callers use e.g. json version 2 while keeping version 1 around.

**Comment by shwestrick** [comment]
Excellent! The `--json-version` thing is a great idea, thanks. I'll try throwing this together soon and let you know how it goes.

**Pull request merged**
